theme = 'gruvbox_dark_hard'

[editor]
color-modes = true
true-color = true
bufferline = 'multiple'
completion-trigger-len = 1
auto-pairs = true
line-number = "relative"
auto-format= false
mouse = true
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true

[keys.normal]
C-l = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-s = ':wa'

ret = 'goto_word'

[editor.inline-diagnostics]
cursor-line = "error"
# other-lines = "error"

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
goto-reference-include-declaration = false
display-inlay-hints = true
display-progress-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["version-control", "read-only-indicator"]
right = ["register", "position", "diagnostics", "file-type"]
separator = "|"
mode.normal	= "NORMAL"
mode.insert	= "INSERT"
mode.select	= "SELECT"

[editor.file-picker]
hidden = false

[keys.normal.backspace]
backspace = "suspend"

# Yazi
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]

# Lazygit
g = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
  ":reload-all"
]
